var apigClientFactory={};apigClientFactory.newClient=function(config){var apigClient={};if(config===undefined){config={accessKey:'',secretKey:'',sessionToken:'',region:'',apiKey:undefined,defaultContentType:'application/json',defaultAcceptType:'application/json'};}
if(config.accessKey===undefined){config.accessKey='';}
if(config.secretKey===undefined){config.secretKey='';}
if(config.apiKey===undefined){config.apiKey='';}
if(config.sessionToken===undefined){config.sessionToken='';}
if(config.region===undefined){config.region='ap-southeast-2';}
if(config.defaultContentType===undefined){config.defaultContentType='application/json';}
if(config.defaultAcceptType===undefined){config.defaultAcceptType='application/json';}
var invokeUrl='https://ydof20cshi.execute-api.ap-southeast-2.amazonaws.com/prod';var endpoint=/(^https?:\/\/[^\/]+)/g.exec(invokeUrl)[1];var pathComponent=invokeUrl.substring(endpoint.length);var sigV4ClientConfig={accessKey:config.accessKey,secretKey:config.secretKey,sessionToken:config.sessionToken,serviceName:'execute-api',region:config.region,endpoint:endpoint,defaultContentType:config.defaultContentType,defaultAcceptType:config.defaultAcceptType};var authType='NONE';if(sigV4ClientConfig.accessKey!==undefined&&sigV4ClientConfig.accessKey!==''&&sigV4ClientConfig.secretKey!==undefined&&sigV4ClientConfig.secretKey!==''){authType='AWS_IAM';}
var simpleHttpClientConfig={endpoint:endpoint,defaultContentType:config.defaultContentType,defaultAcceptType:config.defaultAcceptType};var apiGatewayClient=apiGateway.core.apiGatewayClientFactory.newClient(simpleHttpClientConfig,sigV4ClientConfig);apigClient.rootPost=function(params,body,additionalParams){if(additionalParams===undefined){additionalParams={};}
apiGateway.core.utils.assertParametersDefined(params,[],['body']);var rootPostRequest={verb:'post'.toUpperCase(),path:pathComponent+ uritemplate('/').expand(apiGateway.core.utils.parseParametersToObject(params,[])),headers:apiGateway.core.utils.parseParametersToObject(params,[]),queryParams:apiGateway.core.utils.parseParametersToObject(params,[]),body:body};return apiGatewayClient.makeRequest(rootPostRequest,authType,additionalParams,config.apiKey);};apigClient.rootOptions=function(params,body,additionalParams){if(additionalParams===undefined){additionalParams={};}
apiGateway.core.utils.assertParametersDefined(params,[],['body']);var rootOptionsRequest={verb:'options'.toUpperCase(),path:pathComponent+ uritemplate('/').expand(apiGateway.core.utils.parseParametersToObject(params,[])),headers:apiGateway.core.utils.parseParametersToObject(params,[]),queryParams:apiGateway.core.utils.parseParametersToObject(params,[]),body:body};return apiGatewayClient.makeRequest(rootOptionsRequest,authType,additionalParams,config.apiKey);};apigClient.sendmsqPost=function(params,body,additionalParams){if(additionalParams===undefined){additionalParams={};}
apiGateway.core.utils.assertParametersDefined(params,[],['body']);var sendmsqPostRequest={verb:'post'.toUpperCase(),path:pathComponent+ uritemplate('/contact-us').expand(apiGateway.core.utils.parseParametersToObject(params,[])),headers:apiGateway.core.utils.parseParametersToObject(params,[]),queryParams:apiGateway.core.utils.parseParametersToObject(params,[]),body:body};return apiGatewayClient.makeRequest(sendmsqPostRequest,authType,additionalParams,config.apiKey);};apigClient.sendmsqOptions=function(params,body,additionalParams){if(additionalParams===undefined){additionalParams={};}
apiGateway.core.utils.assertParametersDefined(params,[],['body']);var sendmsqOptionsRequest={verb:'options'.toUpperCase(),path:pathComponent+ uritemplate('/contact-us').expand(apiGateway.core.utils.parseParametersToObject(params,[])),headers:apiGateway.core.utils.parseParametersToObject(params,[]),queryParams:apiGateway.core.utils.parseParametersToObject(params,[]),body:body};return apiGatewayClient.makeRequest(sendmsqOptionsRequest,authType,additionalParams,config.apiKey);};apigClient.sendmsqMsgGet=function(params,body,additionalParams){if(additionalParams===undefined){additionalParams={};}
apiGateway.core.utils.assertParametersDefined(params,['msg'],['body']);var sendmsqMsgGetRequest={verb:'get'.toUpperCase(),path:pathComponent+ uritemplate('/contact-us/{msg}').expand(apiGateway.core.utils.parseParametersToObject(params,['msg'])),headers:apiGateway.core.utils.parseParametersToObject(params,[]),queryParams:apiGateway.core.utils.parseParametersToObject(params,[]),body:body};return apiGatewayClient.makeRequest(sendmsqMsgGetRequest,authType,additionalParams,config.apiKey);};apigClient.sendmsqMsgOptions=function(params,body,additionalParams){if(additionalParams===undefined){additionalParams={};}
apiGateway.core.utils.assertParametersDefined(params,[],['body']);var sendmsqMsgOptionsRequest={verb:'options'.toUpperCase(),path:pathComponent+ uritemplate('/contact-us/{msg}').expand(apiGateway.core.utils.parseParametersToObject(params,[])),headers:apiGateway.core.utils.parseParametersToObject(params,[]),queryParams:apiGateway.core.utils.parseParametersToObject(params,[]),body:body};return apiGatewayClient.makeRequest(sendmsqMsgOptionsRequest,authType,additionalParams,config.apiKey);};return apigClient;};